/* Navigation tree + page content for everything that is not a component page. */
(function () {
  const NS = window.NS;
  const { h2, h3, table, dd, notice, cards, stage, codeBlock } = NS;
  const FIGMA = "https://www.figma.com/design/VZxmDNQiosTN6gqnvEQ65Z/NorthStar-Design-System";
  NS.FIGMA = FIGMA;
  NS.VERSION = "v1.4.0";

  /* ---------- Navigation (Carbon-style left nav) ---------- */
  NS.NAV = [
    { group: "Getting started", items: [["", "Home"], ["getting-started/about", "About NorthStar"], ["getting-started/designers", "Designers"], ["getting-started/developers", "Developers"], ["getting-started/adoption", "Adoption guide"], ["changelog", "Changelog"]] },
    { group: "Foundations", items: [["foundations", "Overview"], ["foundations/color", "Color"], ["foundations/typography", "Typography"], ["foundations/spacing", "Spacing and layout"], ["foundations/radius", "Radius"], ["foundations/elevation", "Elevation"], ["foundations/motion", "Motion"], ["foundations/iconography", "Iconography"], ["foundations/themes", "Themes"], ["foundations/tokens", "Token reference"]] },
    { group: "Components", items: [["components", "Overview"], ...NS.COMPONENTS.map((c) => ["components/" + c.id, c.name, c.status === "New" ? "New" : ""])] },
    { group: "Patterns", items: [["patterns/production", "Production patterns", "New"], ["patterns/create-partner", "Create partner workflow", "New"], ["patterns/forms", "Forms"], ["patterns/modal-dialogs", "Modal dialogs"], ["patterns/table-views", "Table views"], ["patterns/empty-states", "Empty states"], ["patterns/loading", "Loading"], ["patterns/search-filter", "Search and filter"], ["patterns/errors", "Errors"]] },
    { group: "Data visualization", items: [["data-viz", "Overview"], ["data-viz/palettes", "Color palettes"], ["data-viz/sankey", "Sankey chart", "New"], ["data-viz/charts", "Chart types"]] },
    { group: "Floorplans", items: [["floorplans", "Overview"], ["floorplans/dashboard", "Dashboard"], ["floorplans/analytical-list", "Analytical list"], ["floorplans/object-detail", "Object detail"], ["floorplans/wizard", "Guided wizard"], ["floorplans/approval-queue", "Approval queue"]] },
    { group: "Accessibility", items: [["accessibility", "Principles"], ["accessibility/checklist", "Checklist"], ["accessibility/wcag", "WCAG mapping"], ["accessibility/contrast", "Contrast checker", "Tool"]] },
    { group: "Live tools", items: [["tools/live-builder", "Live Builder", "Live"], ["tools/ai", "AI generator", "AI"], ["tools/token-editor", "Token editor"], ["tools/embed", "Embed mode"]] },
    { group: "Community", items: [["community/contributing", "Contributing"], ["community/governance", "Governance"], ["community/carbon-parity", "Carbon parity", "New"], ["community/support", "Support"]] },
  ];

  const hex = (t) => NS.tokenValue(t);
  const swatchBtn = (token, label) => `<button class="swatch" data-copy="var(${token})" title="Copy var(${token})"><i style="background:var(${token})"></i><b>${label || token.replace("--ns-", "")}</b><span>${token}</span></button>`;

  /* ---------- Pages: path -> { title, lede, status, body() } ---------- */
  NS.PAGES = {};
  const P = (path, def) => (NS.PAGES[path] = def);

  /* HOME */
  P("", {
    title: "Home", home: true, noTitle: true,
    init: () => {
      const stopHome = NS.homeInit(document.getElementById("main-content"));
      NS.pageCleanup = stopHome;
    },
    body: () => NS.homeBody(),
  });

  P("getting-started/about", {
    title: "About NorthStar", lede: "NorthStar is an open, token-first design system for enterprise command consoles: dense data, dark surfaces, and workflows where mistakes are expensive.",
    body: () => `${h2("What is NorthStar")}<p>NorthStar is the working code, design tools, guidelines, and community for teams that build operational software. It has four layers:</p><ul><li><strong>Foundations</strong>: primitive ramps mapped to semantic roles for color, type, spacing, radius, motion, elevation, and layout.</li><li><strong>Components</strong>: ${NS.COMPONENTS.length} accessible building blocks with Figma parity.</li><li><strong>Patterns and floorplans</strong>: proven combinations for forms, tables, dialogs, and whole pages.</li><li><strong>Live tools</strong>: token editor, Live Builder, and an AI generator that only speaks in NorthStar tokens.</li></ul>
${h2("Principles")}${cards([{ title: "Clarity at density", color: "teal", body: "Dense screens stay readable through hierarchy, alignment, and restraint, not by removing data.", href: "#/foundations/typography" }, { title: "Tokens, not values", color: "purple", body: "Components consume semantic roles. Themes and brands swap by mode, never by editing components.", href: "#/foundations/tokens" }, { title: "Accessible by default", color: "blue", body: "AA contrast, visible focus, and full keyboard paths ship in every component.", href: "#/accessibility" }])}
${h2("How it is built")}<p>The Figma file is the design source of truth. Variables in Figma map 1:1 to CSS custom properties in <code>tokens.css</code>. Components in <code>components.css</code> and the React package read only those properties, so a change to a token lands everywhere at once.</p>${codeBlock("Figma variable        CSS custom property\ninteractive/primary   --ns-interactive-primary\nbackground/elevated   --ns-background-elevated\nfocus/ring            --ns-focus-ring\nspacing/5 (16px)      --ns-space-5", "text")}`,
  });

  P("getting-started/designers", {
    title: "Designers", lede: "Everything a designer needs to start: the library, how to use variables, and how to hand off without redlines.",
    body: () => `${h2("Get the library")}<ol><li>Open the <a href="${FIGMA}" target="_blank" rel="noopener">NorthStar Figma file</a> and duplicate it or enable it as a team library.</li><li>Turn on the NorthStar variable collections: Primitives, Semantic (Dark / Light modes), Spacing, Radius, Motion.</li><li>Use published text styles (Headline / H1 to Buttons / Primary) rather than local formatting.</li></ol>
${h2("Work with variables")}${dd('<span class="ns-tag ns-tag--teal">interactive/primary</span>', "Bind fills to semantic variables. Mode switching handles dark and light.", '<span class="ns-tag ns-tag--red">#023AFF</span>', "Paste raw hex values. They break theming and accessibility checks.")}
${h2("Handoff")}<p>Dev Mode shows variable names that match the CSS tokens exactly. No redlines needed: if a value is not a token, it is a bug in the design.</p>`,
  });

  P("getting-started/developers", {
    title: "Developers", lede: "Install NorthStar, load the tokens, and ship your first screen in minutes.",
    body: () => `${h2("Install")}${codeBlock("npm install @northstar/react @northstar/tokens", "text")}
${h2("Import tokens")}${codeBlock("import '@northstar/tokens/tokens.css';\nimport '@northstar/react/components.css';", "js")}
${h2("Use a component")}${codeBlock("import { Button, TextInput } from '@northstar/react';\n\nexport function Rename() {\n  return (\n    <form>\n      <TextInput id=\"name\" label=\"Cluster name\" />\n      <Button kind=\"primary\">Save</Button>\n    </form>\n  );\n}", "js")}
${h2("No framework?")}<p>Link the two stylesheets and use the class names shown on every component's Code tab.</p>${codeBlock('<link rel="stylesheet" href="css/tokens.css">\n<link rel="stylesheet" href="css/components.css">\n\n<button class="ns-btn">Deploy</button>', "html")}
${h2("Theme switching")}${codeBlock("document.documentElement.dataset.theme = 'light'; // or remove for dark", "js")}`,
  });

  P("getting-started/adoption", {
    title: "Adoption guide", lede: "A staged path for moving a product onto NorthStar without a big-bang rewrite.",
    body: () => `${h2("Stages")}<ol class="ns-steps" style="margin-bottom:32px"><li class="is-done"><b>1. Tokens</b>Load tokens.css, map legacy colors</li><li class="is-done"><b>2. Shell</b>Header, side nav, page grid</li><li class="is-current"><b>3. Components</b>Replace forms, tables, dialogs</li><li><b>4. Patterns</b>Adopt floorplans</li></ol>
${h2("Adoption checklist")}<div class="ns" style="display:grid;gap:12px">${["Tokens loaded before any product CSS", "No raw hex values in product code (lint rule on)", "Focus ring visible on every interactive element", "Header and side navigation use NorthStar components", "Tables use the data table component", "Destructive actions confirm in a modal", "Dark and light themes both verified", "Contrast checker passes for custom surfaces"].map((t, i) => `<label class="ns-check"><input type="checkbox" data-adopt="${i}"/> ${t}</label>`).join("")}</div><p class="mt" id="adopt-score" style="color:var(--ns-text-tertiary)">Progress is saved in this browser.</p>`,
    init: () => {
      const KEY = "ns-adopt";
      let saved = []; try { saved = JSON.parse(localStorage.getItem(KEY) || "[]"); } catch (e) {}
      const boxes = document.querySelectorAll("[data-adopt]");
      const score = () => { const n = [...boxes].filter((b) => b.checked).length; document.getElementById("adopt-score").textContent = `${n} of ${boxes.length} complete. Progress is saved in this browser.`; };
      boxes.forEach((b) => { b.checked = saved.includes(+b.dataset.adopt); b.addEventListener("change", () => { const s = [...boxes].filter((x) => x.checked).map((x) => +x.dataset.adopt); try { localStorage.setItem(KEY, JSON.stringify(s)); } catch (e) {} score(); }); });
      score();
    },
  });

  P("changelog", {
    title: "Changelog", lede: "What changed, when, and what you need to do about it.",
    body: () => `${h2(NS.VERSION + " (October 2026)")}<p><span class="ns-tag ns-tag--green">Minor</span></p><ul><li><strong>New</strong>: Sankey chart (S / M / L, minimum and maximum data, with and without background).</li><li><strong>New</strong>: Date picker and File uploader components.</li><li><strong>New</strong>: Live Builder, AI generator, and token editor on the docs site.</li><li><strong>Changed</strong>: focus ring moved to <code>--ns-teal-500</code> in dark mode for 3:1 on every surface.</li><li><strong>Docs</strong>: Accessibility checklist and WCAG mapping pages.</li></ul>
${h2("v1.3.0 (July 2026)")}<ul><li>Light theme override layer. All semantic roles now have light values.</li><li>Radius scale expanded to <code>2xl</code>, <code>3xl</code>, and <code>full</code>.</li><li>Data table: batch action bar and select-all.</li></ul>
${h2("v1.2.0 (April 2026)")}<ul><li>Motion tokens: <code>duration/*</code> and <code>easing/*</code>, with reduced-motion fallback.</li><li>Elevation levels 01 to 04.</li></ul>
${h2("Migration notes")}${notice("warning", "Renamed in v1.4", "<code>--ns-accent</code> is now <code>--ns-text-accent</code>. The old name is aliased until v2.0.")}`,
  });

  /* FOUNDATIONS */
  P("foundations", {
    title: "Foundations overview", lede: "NorthStar foundations coordinate design intent with technical reality. Every visual decision maps to a token, so themes switch instantly across devices.",
    body: () => `${h2("The foundations")}${cards([
      { title: "Color", color: "teal", body: "Primitive ramps and semantic roles for Light and Dark themes.", href: "#/foundations/color", go: "View" },
      { title: "Typography", color: "purple", body: "A compact hierarchy for dense interfaces and dashboard emphasis.", href: "#/foundations/typography", go: "View" },
      { title: "Spacing and layout", color: "blue", body: "A 15-step spacing scale, 12-column grid, and four breakpoints.", href: "#/foundations/spacing", go: "View" },
      { title: "Radius", color: "green", body: "From precise technical controls to fully rounded status elements.", href: "#/foundations/radius", go: "View" },
      { title: "Elevation", color: "yellow", body: "Four levels that clarify hierarchy without noise.", href: "#/foundations/elevation", go: "View" },
      { title: "Motion", color: "red", body: "Durations and easing that communicate state change.", href: "#/foundations/motion", go: "View" },
    ])}
${h2("Token architecture")}<p>Primitive tokens hold raw values. Semantic tokens reference primitives and carry meaning. Components consume only semantic tokens.</p>${codeBlock("/* primitive */\n--ns-blue-500: #023aff;\n\n/* semantic (dark) */\n--ns-interactive-primary: var(--ns-blue-500);\n\n/* component */\n.ns-btn { background: var(--ns-interactive-primary); }", "css")}`,
  });

  P("foundations/color", {
    title: "Color System", lede: "Our enterprise color structure is divided into primitive scale ramps and strict semantic roles mapping directly to dark and light templates.",
    body: () => `${h2("Color philosophy")}<p>Color carries meaning first and brand second. Navy and near-black surfaces keep dense data calm; teal, blue, and purple mark what is interactive or important; status colors are reserved for status.</p>
${h2("Primitive ramps")}${h3("Brand")}<div class="grid grid-4">${swatchBtn("--ns-navy-900", "Navy 900")}${swatchBtn("--ns-blue-500", "Blue 500")}${swatchBtn("--ns-purple-500", "Purple 500")}${swatchBtn("--ns-green-500", "Green 500")}${swatchBtn("--ns-teal-500", "Teal 500")}${swatchBtn("--ns-persian-500", "Persian blue")}${swatchBtn("--ns-yellow-500", "Yellow 500")}${swatchBtn("--ns-red-400", "Red 400")}</div>
${h3("Gray")}<div class="ramp">${Array.from({ length: 11 }, (_, i) => `<button data-copy="var(--ns-gray-${i})" title="Copy var(--ns-gray-${i})"><i style="background:var(--ns-gray-${i})"></i><span>${i}<br>${hex("--ns-gray-" + i)}</span></button>`).join("")}</div>
${h2("Best practices")}${dd('<button class="ns-btn">Deploy</button>', "Use <code>interactive-primary</code> for action buttons. This keeps contrast correct and maps modes automatically.", '<button class="ns-btn" style="background:#023AFF">Deploy</button>', "Hardcode raw hex like <code>#023AFF</code> into layouts. It bypasses the accessibility and theme layers.")}
${h2("Semantic tokens")}<p>Values shown are for the current theme. Toggle the theme in the header and they update.</p>${semanticTable()}`,
  });

  function semanticTable() {
    const groups = { background: ["primary", "secondary", "surface", "elevated", "shell", "selected"], text: ["primary", "secondary", "tertiary", "disabled", "link", "accent"], border: ["subtle", "default", "strong"], interactive: ["primary", "primary-hover", "secondary"], focus: ["ring"], status: ["success", "warning", "error", "info"] };
    const r = [];
    Object.entries(groups).forEach(([g, list]) => list.forEach((n) => { const t = `--ns-${g}-${n}`; r.push(`<tr class="tok-row" data-copy="var(${t})"><td><span class="chip" style="background:var(${t})"></span><code>${g}/${n}</code></td><td><code>${t}</code></td><td><code>${hex(t)}</code></td></tr>`); }));
    return `<div class="dtable-wrap"><table class="dtable"><thead><tr><th>Role</th><th>Token</th><th>Value</th></tr></thead><tbody>${r.join("")}</tbody></table></div>`;
  }

  P("foundations/typography", {
    title: "Typography", lede: "A compact hierarchy for data-dense interfaces, readable content, and clear dashboard emphasis. Open Sans for UI and content, JetBrains Mono for data and code.",
    body: () => {
      const styles = [["Headline / H1", "h1"], ["Headline / H2", "h2"], ["Headline / H3", "h3"], ["Headline / H4", "h4"], ["Headline / H5", "h5"], ["Headline / H6", "h6"], ["Body / Title", "title"], ["Body / Body 1", "body1"], ["Body / Body 2", "body2"], ["Body / Body 3", "body3"], ["Tips and details / Caption", "caption"], ["Tips and details / Overline", "overline"], ["Buttons / Primary", "button"]];
      return `${h2("Typefaces")}<div class="grid grid-2"><div class="ns-card"><span class="ns-kpi__label">Sans</span><div style="font:800 44px/1.1 var(--ns-font-sans)">Open Sans</div><p class="ns-card__body">UI, headings, and body. Weights 400, 600, 700, 800.</p></div><div class="ns-card"><span class="ns-kpi__label">Mono</span><div style="font:600 40px/1.1 var(--ns-font-mono)">JetBrains</div><p class="ns-card__body">Numbers, IDs, logs, and code. Tabular figures by default.</p></div></div>
${h2("Type scale")}<p>Use published text styles rather than local formatting. Headings create structure; body and caption styles carry operational content.</p>
<div class="dtable-wrap"><table class="dtable"><thead><tr><th>Sample</th><th>Style</th><th>Size / line</th></tr></thead><tbody>${styles.map(([n, k]) => { const size = hex(`--ns-type-${k}-size`), line = hex(`--ns-type-${k}-line`); const w = hex(`--ns-type-${k}-weight`) || (k === "overline" || k === "button" ? 700 : k === "title" ? 600 : 400); return `<tr><td style="font:${w} ${size}/${line} var(--ns-font-sans);${k === "overline" ? "text-transform:uppercase;letter-spacing:1.5px;" : ""}white-space:nowrap;color:var(--ns-text-primary)">NorthStar</td><td><code>${n}</code></td><td><code>${size} / ${line}</code></td></tr>`; }).join("")}</tbody></table></div>
${h2("Data typography")}${stage('<div style="display:flex;gap:40px;flex-wrap:wrap"><div class="ns-kpi"><span class="ns-kpi__label">Throughput</span><span class="ns-kpi__value">48,209</span><span class="ns-kpi__delta">↑ 12.4%</span></div><div style="font:400 13px/1.7 var(--ns-font-mono);color:var(--ns-text-secondary)">node-07  cpu 71.2%  mem 12.4G<br>node-08  cpu 33.9%  mem  8.1G<br>node-09  cpu 90.4%  mem 15.8G</div></div>', { label: "Numbers in mono align in columns", code: false })}
${h2("Best practices")}${dd('<div style="text-align:left"><div style="font:700 20px/28px var(--ns-font-sans)">Cluster health</div><div style="font:400 14px/20px var(--ns-font-sans);color:var(--ns-text-secondary)">3 nodes need attention</div></div>', "Use two or three styles per region.", '<div style="text-align:left"><div style="font:800 28px var(--ns-font-sans)">Cluster</div><div style="font:600 18px var(--ns-font-sans)">Health</div><div style="font:italic 15px serif">3 nodes</div></div>', "Mix many sizes, weights, and families in one card.")}`;
    },
  });

  P("foundations/spacing", {
    title: "Spacing and layout", lede: "A consistent spacing scale governs padding, gaps, alignment, and rhythm. Responsive breakpoints and a 12-column grid support dashboards from compact to wide.",
    body: () => `${h2("Spacing scale")}<p>Start with the smallest token that preserves clarity. Prefer token steps over one-off measurements.</p><div class="dtable-wrap"><table class="dtable"><thead><tr><th>Token</th><th>Value</th><th></th></tr></thead><tbody>${Array.from({ length: 15 }, (_, i) => `<tr class="tok-row" data-copy="var(--ns-space-${i})"><td><code>spacing/${i}</code></td><td><code>${hex("--ns-space-" + i)}</code></td><td><span style="display:inline-block;height:14px;width:calc(var(--ns-space-${i}) * 2.4);min-width:2px;border-radius:2px;background:var(--ns-gradient-brand)"></span></td></tr>`).join("")}</tbody></table></div>
${h2("Common uses")}${table(["Token", "Use"], [["<code>space-3</code> 8px", "Micro padding, tight control spacing"], ["<code>space-5</code> 16px", "Component-level margins and gaps"], ["<code>space-7</code> 24px", "Card padding, grid gutter"], ["<code>space-8</code> 32px", "Standard structural divisions"]])}
${h2("Breakpoints")}${table(["Token", "Min width", "Columns", "Use"], [["<code>breakpoint/compact</code>", "480px", "4", "Phones"], ["<code>breakpoint/medium</code>", "768px", "8", "Tablets, narrow windows"], ["<code>breakpoint/expanded</code>", "1280px", "12", "Laptops"], ["<code>breakpoint/wide</code>", "1600px", "12", "Wall displays, NOC screens"]])}
${h2("Grid")}<p>12 columns, 24px gutter, content max-width 1440px. Design mobile-first, then increase density and column count as width grows.</p>${stage(`<div style="display:grid;grid-template-columns:repeat(12,1fr);gap:var(--ns-grid-gutter);width:100%">${Array.from({ length: 12 }, (_, i) => `<div style="height:72px;border-radius:4px;background:color-mix(in srgb,var(--ns-teal-500) 16%,transparent);border:1px dashed color-mix(in srgb,var(--ns-teal-500) 50%,transparent);display:grid;place-items:center;font:600 11px var(--ns-font-mono);color:var(--ns-text-accent)">${i + 1}</div>`).join("")}<div style="grid-column:span 8;height:56px;border-radius:6px;background:var(--ns-background-elevated);display:grid;place-items:center;font-size:12px">span 8</div><div style="grid-column:span 4;height:56px;border-radius:6px;background:var(--ns-background-elevated);display:grid;place-items:center;font-size:12px">span 4</div></div>`, { label: "12-column grid", block: true, code: false })}`,
  });

  P("foundations/radius", {
    title: "Radius", lede: "Corner treatments range from precise technical controls to fully rounded status elements.",
    body: () => { const r = ["none", "xs", "sm", "md", "lg", "xl", "2xl", "3xl", "full"]; return `${h2("Radius scale")}<p>Use smaller radii for dense controls and larger radii for cards, panels, and expressive containers.</p><div class="grid grid-auto" style="grid-template-columns:repeat(auto-fill,minmax(110px,1fr))">${r.map((k) => `<button class="swatch" data-copy="var(--ns-radius-${k})"><i style="height:80px;background:var(--ns-gradient-bruise);border-radius:var(--ns-radius-${k})"></i><b>${k}</b><span>${hex("--ns-radius-" + k)}</span></button>`).join("")}</div>
${h2("Mapping")}${table(["Element", "Token"], [["Checkbox", "<code>radius-xs</code>"], ["Inputs, selects, tooltips", "<code>radius-sm</code>"], ["Buttons", "<code>radius-md</code>"], ["Cards, tables, popovers", "<code>radius-lg</code>"], ["Modals", "<code>radius-xl</code>"], ["Tags, toggles, avatars, search", "<code>radius-full</code>"]])}`; },
  });

  P("foundations/elevation", {
    title: "Elevation", lede: "Elevation clarifies hierarchy without overwhelming dense interfaces. Use the lowest level that communicates the relationship.",
    body: () => `${h2("Levels")}<div class="grid grid-4">${[["01", "Subtle separation for controls and cards."], ["02", "Menus, popovers, and sticky regions."], ["03", "Dialogs and elevated panels."], ["04", "Maximum elevation for critical overlays."]].map(([n, d]) => `<button class="swatch" data-copy="var(--ns-elevation-${n})" style="padding:24px"><i style="height:96px;background:var(--ns-background-elevated);box-shadow:var(--ns-elevation-${n});border-radius:var(--ns-radius-lg)"></i><b>Elevation/${n}</b><span style="font-family:var(--ns-font-sans)">${d}</span></button>`).join("")}</div>
${h2("In dark mode")}<p>Shadows are weak on near-black, so NorthStar raises elevated surfaces to <code>background/elevated</code> (Navy 900) and pairs shadows with a hairline border. Level 04 adds a faint blue glow.</p>`,
  });

  P("foundations/motion", {
    title: "Motion", lede: "Motion communicates state change. Use fast durations for local feedback and slower ones only for large spatial transitions. Reduced-motion preferences are respected automatically.",
    body: () => `${h2("Duration")}${table(["Token", "Value", "Use"], [["<code>duration/instant</code>", "0ms", "Reduced motion, immediate swaps"], ["<code>duration/fast</code>", "100ms", "Hover, press, color changes"], ["<code>duration/base</code>", "200ms", "Toggles, tooltips, small reveals"], ["<code>duration/slow</code>", "320ms", "Modals, drawers, progress fills"], ["<code>duration/expressive</code>", "500ms", "Page-level and hero transitions"]])}
${h2("Easing")}${table(["Token", "Curve", "Use"], [["<code>easing/standard</code>", "cubic-bezier(0.2, 0, 0, 1)", "Things that move on screen"], ["<code>easing/enter</code>", "cubic-bezier(0, 0, 0, 1)", "Things that appear"], ["<code>easing/exit</code>", "cubic-bezier(0.3, 0, 1, 1)", "Things that leave"]])}
${h2("Try it")}<div class="stage"><div class="stage__bar"><span class="lbl">Motion lab</span><div class="ns seg" id="mo-seg">${["fast", "base", "slow", "expressive"].map((d, i) => `<button data-d="${d}" aria-pressed="${i === 2}">${d}</button>`).join("")}</div></div><div class="stage__canvas ns is-block"><div style="display:grid;gap:14px;max-width:560px;margin:0 auto">${["standard", "enter", "exit"].map((e) => `<div style="display:grid;grid-template-columns:80px 1fr;align-items:center;gap:12px"><code style="font-size:12px;color:var(--ns-text-secondary)">${e}</code><div style="position:relative;height:28px;background:var(--ns-background-secondary);border-radius:14px"><span class="mo-dot" data-e="${e}" style="position:absolute;left:2px;top:2px;width:24px;height:24px;border-radius:50%;background:var(--ns-gradient-brand)"></span></div></div>`).join("")}<button class="ns-btn" id="mo-go" style="justify-self:start">Play</button></div></div></div>`,
    init: () => {
      let d = "slow", on = false;
      document.querySelectorAll("#mo-seg button").forEach((b) => b.addEventListener("click", () => { d = b.dataset.d; document.querySelectorAll("#mo-seg button").forEach((x) => x.setAttribute("aria-pressed", x === b)); }));
      document.getElementById("mo-go").addEventListener("click", () => { on = !on; document.querySelectorAll(".mo-dot").forEach((dot) => { dot.style.transition = `left var(--ns-duration-${d}) var(--ns-easing-${dot.dataset.e})`; dot.style.left = on ? "calc(100% - 26px)" : "2px"; }); });
    },
  });

  const ICONS = { add: "M12 5v14M5 12h14", close: "M6 6l12 12M18 6 6 18", check: "m5 12 5 5 9-10", search: "M11 18a7 7 0 1 0 0-14 7 7 0 0 0 0 14Zm9 2-3.5-3.5", chevron: "m9 6 6 6-6 6", refresh: "M20 11a8 8 0 1 0-2.3 5.7M20 5v6h-6", settings: "M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm7.4-3a7.4 7.4 0 0 0-.1-1.3l2-1.6-2-3.4-2.4 1a7 7 0 0 0-2.2-1.3L14.3 3h-4l-.4 2.4a7 7 0 0 0-2.2 1.3l-2.4-1-2 3.4 2 1.6a7.4 7.4 0 0 0 0 2.6l-2 1.6 2 3.4 2.4-1a7 7 0 0 0 2.2 1.3l.4 2.4h4l.4-2.4a7 7 0 0 0 2.2-1.3l2.4 1 2-3.4-2-1.6c.1-.4.1-.9.1-1.3Z", alert: "M12 9v4m0 4h.01M10.3 3.9 2.4 18a2 2 0 0 0 1.7 3h15.8a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z", info: "M12 16v-4m0-4h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z", user: "M20 21a8 8 0 0 0-16 0M12 13a5 5 0 1 0 0-10 5 5 0 0 0 0 10Z", download: "M12 3v12m0 0-5-5m5 5 5-5M4 21h16", upload: "M12 21V9m0 0-5 5m5-5 5 5M4 3h16", filter: "M3 5h18l-7 8v6l-4 2v-8L3 5Z", lock: "M6 11h12v10H6zM8 11V7a4 4 0 1 1 8 0v4", server: "M4 4h16v6H4zM4 14h16v6H4zM8 7h.01M8 17h.01", chart: "M4 20V10m6 10V4m6 16v-7m4 7H2", bell: "M18 8a6 6 0 1 0-12 0c0 7-3 9-3 9h18s-3-2-3-9M13.7 21a2 2 0 0 1-3.4 0", link: "M10 14a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-1 1m2 5a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l1-1", trash: "M3 6h18M8 6V4h8v2m-9 0 1 14h8l1-14", edit: "M4 20h4L19 9l-4-4L4 16v4Z", copy: "M9 9h11v11H9zM5 15H4V4h11v1", globe: "M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20ZM2 12h20M12 2a15 15 0 0 1 0 20 15 15 0 0 1 0-20" };
  NS.svgIcon = (n, s = 20) => `<svg width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${ICONS[n]}"/></svg>`;
  NS.ICONS = null;
  NS.loadIcons = async () => {
    if (NS.ICONS) return NS.ICONS;
    const list = await (await fetch("assets/icons/manifest.json")).json();
    await Promise.all(list.map(async (ic) => { ic.svg = (await (await fetch("assets/icons/" + ic.file)).text()).replace(/<\?xml[^>]*>/, ""); }));
    return (NS.ICONS = list);
  };
  P("foundations/iconography", {
    title: "Iconography", figma: true, lede: "95 icons exported from the Figma Icons page: a 24px set, an 18px mini set, and a status set. Every icon uses currentColor, so it follows text and state tokens.",
    body: () => `<div class="ns" style="display:flex;gap:12px;flex-wrap:wrap;margin-bottom:16px"><div class="ns-search" style="flex:1;min-width:220px">${NS.icon.search}<input class="ns-input" id="ic-q" type="search" placeholder="Search icons" aria-label="Search icons"/></div><div class="seg" id="ic-set">${["All", "24", "mini", "status"].map((z, i) => `<button data-s="${z}" aria-pressed="${i === 0}">${z}</button>`).join("")}</div><div class="seg" id="ic-color">${[["text-primary", "Primary"], ["text-accent", "Accent"], ["status-error", "Error"], ["purple-500", "Purple"]].map(([c, n], i) => `<button data-c="${c}" aria-pressed="${i === 0}">${n}</button>`).join("")}</div></div><p id="ic-count" style="color:var(--ns-text-tertiary);font-size:13px">Loading icons...</p><div id="ic-grid" class="grid" style="grid-template-columns:repeat(auto-fill,minmax(112px,1fr))"></div>
${h2("Sizes")}${table(["Set", "Size", "Use"], [["24", "24px (some 16 to 32)", "Buttons, navigation, standalone"], ["mini", "18px", "Dense controls: sort, filter, menus, links"], ["status", "24px", "Warning, Success, Attention, Question in alerts and toasts"]])}
${h2("Usage")}${codeBlock('<!-- inline, inherits color -->\n<button class="ns-btn ns-btn--outline ns-btn--icon" aria-label="Notifications">\n  <svg viewBox="0 0 24 24">...</svg>\n</button>\n\n<!-- or as a file -->\n<img src="assets/icons/bell-solid.svg" alt="" width="24" height="24">', "html")}
${h2("Best practices")}${dd(`<button class="ns-btn ns-btn--outline ns-btn--icon" aria-label="Refresh">${NS.svgIcon("refresh")}</button>`, "Give icon-only buttons an accessible name and a tooltip.", `<span style="color:var(--ns-status-error)">${NS.svgIcon("check")}</span>`, "Use an icon whose meaning conflicts with its color.")}`,
    init: async () => {
      const grid = document.getElementById("ic-grid"); let set = "All", col = "text-primary";
      let icons; try { icons = await NS.loadIcons(); } catch (e) { document.getElementById("ic-count").textContent = "Icons need the site served over http (python3 -m http.server)."; return; }
      if (!document.getElementById("ic-grid")) return;
      const draw = () => { const q = document.getElementById("ic-q").value.toLowerCase(); const list = icons.filter((i) => (set === "All" || i.set === set) && i.name.toLowerCase().includes(q)); document.getElementById("ic-count").textContent = `${list.length} of ${icons.length} icons. Click to copy SVG.`; grid.innerHTML = list.map((i) => `<button class="swatch" data-icon="${i.file}" style="justify-items:center;padding:18px 8px;color:var(--ns-${col})" title="Copy ${i.name} SVG"><span style="width:28px;height:28px;display:grid;place-items:center">${i.svg.replace("<svg", '<svg width="' + i.size + '" height="' + i.size + '" aria-hidden="true"')}</span><span style="text-align:center">${i.name}</span></button>`).join(""); };
      grid.addEventListener("click", (e) => { const b = e.target.closest("[data-icon]"); if (b) NS.copy(icons.find((i) => i.file === b.dataset.icon).svg); });
      document.getElementById("ic-q").addEventListener("input", draw);
      document.querySelectorAll("#ic-set button").forEach((b) => b.addEventListener("click", () => { set = b.dataset.s; document.querySelectorAll("#ic-set button").forEach((x) => x.setAttribute("aria-pressed", x === b)); draw(); }));
      document.querySelectorAll("#ic-color button").forEach((b) => b.addEventListener("click", () => { col = b.dataset.c; document.querySelectorAll("#ic-color button").forEach((x) => x.setAttribute("aria-pressed", x === b)); draw(); }));
      draw();
    },
  });

  P("foundations/themes", {
    title: "Themes", lede: "Dark is the default. Light is a full override layer on the same semantic roles, so components never change structure between modes.",
    body: () => `${h2("Switching themes")}<p>Set <code>data-theme="light"</code> on <code>&lt;html&gt;</code>. Remove it for dark. The header toggle on this site does exactly that.</p><div class="ns" style="display:flex;gap:12px;margin-bottom:32px"><button class="ns-btn" data-set-theme="dark">Use dark</button><button class="ns-btn ns-btn--tertiary" data-set-theme="light">Use light</button></div>
${h2("Side by side")}<div class="grid grid-2">${["dark", "light"].map((t) => `<div data-theme-preview="${t}" style="border-radius:var(--ns-radius-lg);overflow:hidden;border:1px solid var(--ns-border-default)"><iframe title="${t} theme preview" src="?embed&theme=${t}#/components/notification" style="width:100%;height:420px;border:0;display:block"></iframe></div>`).join("")}</div>
${h2("Brand themes")}<p>Swap primitives to rebrand. Semantic roles and components stay untouched. Try it in the <a href="#/tools/token-editor">token editor</a>.</p>${codeBlock(":root[data-brand=\"partner\"] {\n  --ns-blue-500: #0070f2;\n  --ns-teal-500: #27bdfa;\n  --ns-purple-500: #a78bfa;\n}", "css")}`,
  });

  P("foundations/tokens", {
    title: "Token reference", lede: "Every NorthStar design token as a CSS custom property. Filter, click to copy, and see live values for the current theme.",
    body: () => `<div class="ns" style="display:flex;gap:12px;flex-wrap:wrap;margin-bottom:20px"><div class="ns-search" style="flex:1;min-width:240px">${NS.icon.search}<input class="ns-input" id="tok-filter" type="search" placeholder="Filter tokens, e.g. status, space, radius" aria-label="Filter tokens"/></div><div class="seg" id="tok-cat">${["All", "Color", "Space", "Type", "Radius", "Motion", "Elevation", "Layout"].map((c, i) => `<button data-c="${c}" aria-pressed="${i === 0}">${c}</button>`).join("")}</div></div><p id="tok-count" style="color:var(--ns-text-tertiary);font-size:13px"></p><div id="tok-table"></div>`,
    init: () => {
      const all = NS.allTokens();
      let cat = "All";
      const catOf = (n) => /space/.test(n) ? "Space" : /type|font/.test(n) ? "Type" : /radius/.test(n) ? "Radius" : /duration|easing/.test(n) ? "Motion" : /elevation/.test(n) ? "Elevation" : /breakpoint|content|grid/.test(n) ? "Layout" : "Color";
      const draw = () => {
        const q = document.getElementById("tok-filter").value.toLowerCase();
        const list = all.filter((t) => (cat === "All" || catOf(t) === cat) && t.includes(q));
        document.getElementById("tok-count").textContent = `${list.length} of ${all.length} tokens`;
        document.getElementById("tok-table").innerHTML = `<div class="dtable-wrap"><table class="dtable"><thead><tr><th>Token</th><th>Value</th><th>Category</th></tr></thead><tbody>${list.map((t) => { const v = NS.tokenValue(t); const col = catOf(t) === "Color" && !/gradient/.test(t); return `<tr class="tok-row" data-copy="var(${t})"><td><code>${t}</code></td><td>${col ? `<span class="chip" style="background:var(${t})"></span>` : ""}<code>${NS.esc(v)}</code></td><td>${catOf(t)}</td></tr>`; }).join("")}</tbody></table></div>`;
      };
      document.getElementById("tok-filter").addEventListener("input", draw);
      document.querySelectorAll("#tok-cat button").forEach((b) => b.addEventListener("click", () => { cat = b.dataset.c; document.querySelectorAll("#tok-cat button").forEach((x) => x.setAttribute("aria-pressed", x === b)); draw(); }));
      draw();
    },
  });

  /* COMPONENTS OVERVIEW */
  P("components", {
    title: "Components", lede: "Reusable building blocks, each with a live playground, token table, code, and accessibility guidance. Status shows production readiness.",
    body: () => {
      const cats = [...new Set(NS.COMPONENTS.map((c) => c.cat))];
      return `<div class="ns" style="margin-bottom:24px"><div class="ns-search" style="max-width:420px">${NS.icon.search}<input class="ns-input" id="cmp-filter" type="search" placeholder="Filter components" aria-label="Filter components"/></div></div>
<div id="cmp-grid" class="grid grid-auto">${NS.COMPONENTS.map((c) => `<a class="rcard" href="#/components/${c.id}" data-name="${c.name.toLowerCase()} ${c.cat.toLowerCase()}"><div class="ns" style="height:88px;display:grid;place-items:center;border-radius:6px;background:var(--ns-background-secondary);overflow:hidden;pointer-events:none"><div style="transform:scale(.72)">${thumb(c)}</div></div><h3 style="font-size:16px;line-height:22px">${c.name}</h3><p>${c.cat}</p></a>`).join("")}</div>
${h2("Component status")}<div class="dtable-wrap"><table class="dtable"><thead><tr><th>Component</th><th>Category</th><th>Figma</th><th>React</th><th>HTML/CSS</th><th>Status</th></tr></thead><tbody>${NS.COMPONENTS.map((c) => `<tr><td><a href="#/components/${c.id}">${c.name}</a></td><td>${c.cat}</td><td>✓</td><td>✓</td><td>✓</td><td><span class="ns ns-tag ns-tag--sm ${c.status === "New" ? "ns-tag--teal" : "ns-tag--green"}">${c.status}</span></td></tr>`).join("")}</tbody></table></div>
<p style="color:var(--ns-text-tertiary);font-size:13px">${cats.length} categories: ${cats.join(", ")}.</p>`;
    },
    init: () => { const f = document.getElementById("cmp-filter"); f.addEventListener("input", () => document.querySelectorAll("#cmp-grid .rcard").forEach((c) => (c.style.display = c.dataset.name.includes(f.value.toLowerCase()) ? "" : "none"))); },
  });
  function thumb(c) {
    const d = c.playground.controls ? Object.fromEntries(c.playground.controls.map((k) => [k.key, k.default ?? (k.options ? k.options[0] : k.type === "bool" ? false : "")])) : {};
    if (["data-table", "accordion", "date-picker", "file-uploader", "side-navigation", "modal"].includes(c.id)) return { "data-table": '<div class="ns-table-wrap" style="width:260px"><table class="ns-table ns-table--compact"><tr><th>Partner</th><th>MRR</th></tr><tr><td>Acme</td><td class="num">$12k</td></tr><tr><td>Zeta</td><td class="num">$38k</td></tr></table></div>', accordion: '<div class="ns-accordion" style="width:240px"><details open><summary>Section</summary></details><details><summary>Section</summary></details></div>', "date-picker": '<div class="ns-cal" style="width:220px;padding:10px;transform:scale(.9)"><div class="ns-cal__grid">' + Array.from({ length: 14 }, (_, i) => `<span class="ns-cal__day ${i === 5 ? "is-selected" : ""}">${i + 1}</span>`).join("") + "</div></div>", "file-uploader": '<div class="ns-drop" style="width:240px;padding:16px">↑ Drop files</div>', "side-navigation": '<div class="ns-sidenav" style="width:180px;padding:6px"><a aria-current="page">Dashboard</a><a>Partners</a></div>', modal: '<div class="ns-modal ns-modal--inline" style="width:240px"><div class="ns-modal__head" style="padding:14px"><b style="font-size:14px">Revoke access?</b></div><div class="ns-modal__foot" style="padding:10px"><button class="ns-btn ns-btn--sm ns-btn--danger">Revoke</button></div></div>' }[c.id];
    return c.playground.render(d);
  }

  /* PATTERNS */
  const pattern = (path, title, lede, body) => P("patterns/" + path, { title, lede, body });
  pattern("forms", "Forms", "Forms collect information. NorthStar forms are single-column by default, validate on blur, and summarize errors on submit.", () => `${h2("Single column")}${stage(`<form class="ns" style="display:grid;gap:18px;max-width:420px;width:100%" onsubmit="event.preventDefault();NS.toast('Partner created','Acme Corp was added.','success')"><div class="ns-field"><label class="ns-label" for="f1">Company name</label><input class="ns-input" id="f1" required value="Acme Corp"/></div><div class="ns-field is-error"><label class="ns-label" for="f2">Billing email</label><input class="ns-input" id="f2" value="billing@acme" aria-invalid="true" aria-describedby="f2h"/><span class="ns-helper" id="f2h">Enter a full email address, like billing@acme.com</span></div><div class="ns-field"><label class="ns-label" for="f3">Tier</label><select class="ns-select" id="f3"><option>Gold</option><option>Silver</option></select></div><label class="ns-check"><input type="checkbox" checked/> Send welcome kit</label><div style="display:flex;gap:10px"><button class="ns-btn">Create partner</button><button type="button" class="ns-btn ns-btn--tertiary">Cancel</button></div></form>`, { left: true, label: "Create partner" })}
${h2("Validation")}${table(["When", "Behavior"], [["On blur", "Validate format; show inline error under the field"], ["On submit", "Show a summary notification and move focus to the first error"], ["On fix", "Clear the error as soon as the value is valid"]])}
${h2("Layout")}${dd('<div style="display:grid;gap:8px;width:200px"><div class="ns-skel" style="height:34px"></div><div class="ns-skel" style="height:34px"></div><div class="ns-skel" style="height:34px"></div></div>', "One column, labels on top, in the order people think.", '<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;width:240px"><div class="ns-skel" style="height:34px"></div><div class="ns-skel" style="height:34px"></div><div class="ns-skel" style="height:34px"></div></div>', "Put unrelated fields side by side. It breaks the reading path.")}`);
  pattern("modal-dialogs", "Modal dialogs", "Use modal dialogs for decisions that must happen now. Everything else belongs in the page.", () => `${h2("Types")}${table(["Type", "Use", "Primary action"], [["Passive", "Acknowledge information", "OK"], ["Transactional", "Short task, 1 to 3 fields", "Save, Create"], ["Danger", "Irreversible action", "Delete, Revoke"]])}${h2("Live example")}${stage('<button class="ns-btn ns-btn--danger" data-open-modal>Revoke credentials</button>', { label: "Danger modal with focus trap" })}${h2("Rules")}<ul><li>One modal at a time. Never open a modal from a modal.</li><li>Title says what will happen; primary button repeats the verb.</li><li>Esc and the close button always work, except during a running save.</li></ul>`);
  pattern("table-views", "Table views", "How search, filters, batch actions, and pagination combine around a data table.", () => `${h2("Anatomy")}${stage(`<div style="display:grid;gap:12px;width:100%"><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:center"><div class="ns-search" style="flex:1;min-width:220px">${NS.icon.search}<input class="ns-input" placeholder="Search partners" aria-label="Search partners"/></div><span class="ns-tag ns-tag--blue">Tier: Gold<button aria-label="Remove Tier: Gold">×</button></span><button class="ns-btn ns-btn--tertiary ns-btn--sm">Filters</button></div>${NS.COMPONENTS.find((c) => c.id === "data-table").playground.render({ size: "Default", batch: true })}<nav class="ns-pagination" style="justify-content:flex-end"><button class="ns-page" disabled>‹</button><button class="ns-page" aria-current="page">1</button><button class="ns-page">2</button><button class="ns-page">›</button></nav></div>`, { block: true, label: "Toolbar, table, pagination", code: false })}${h2("Rules")}<ul><li>Search and filters sit above the table; active filters show as dismissible tags.</li><li>Selecting rows replaces the toolbar with a batch action bar.</li><li>Keep the header row sticky for long tables.</li></ul>`);
  pattern("empty-states", "Empty states", "Empty states explain why there is nothing here and what to do next.", () => `${h2("Variants")}<div class="grid grid-3">${[["First use", "No partners yet", "Invite your first partner to start syncing data.", "Invite partner"], ["No results", "No matches", "Try removing a filter or checking spelling.", "Clear filters"], ["Error", "Could not load", "The service did not respond. Your data is safe.", "Retry"]].map(([k, t, b, a]) => `<div class="ns ns-card" style="text-align:center;justify-items:center;padding:36px 24px"><span class="ns-tag ns-tag--sm">${k}</span><span style="color:var(--ns-text-tertiary)">${NS.svgIcon(k === "Error" ? "alert" : k === "No results" ? "search" : "user", 32)}</span><h3 class="ns-card__title">${t}</h3><p class="ns-card__body">${b}</p><button class="ns-btn ns-btn--sm ${k === "First use" ? "" : "ns-btn--tertiary"}">${a}</button></div>`).join("")}</div>`);
  pattern("loading", "Loading", "Choose the loading treatment by how long the wait is and how much of the page is affected.", () => `${h2("Choosing")}${table(["Wait", "Scope", "Use"], [["< 300ms", "Any", "Nothing"], ["300ms to 2s", "Component", "Spinner or button loading state"], ["300ms to 2s", "Page or card", "Skeleton"], ["> 2s", "Task", "Progress bar with label"]])}${h2("Examples")}${stage('<div style="display:grid;gap:10px;width:260px"><div class="ns-skel" style="height:18px;width:50%"></div><div class="ns-skel" style="height:60px"></div></div><button class="ns-btn" aria-busy="true"><span class="ns-spin"></span>Saving</button><div class="ns-progress" style="width:240px"><div class="ns-progress__meta"><span>Importing 3 of 12</span><span>25%</span></div><div class="ns-progress__track"><div class="ns-progress__bar" style="--_v:25%"></div></div></div>', { code: false })}`);
  pattern("search-filter", "Search and filter", "Search narrows by keyword; filters narrow by attribute. Show both states clearly and make them easy to undo.", () => `${h2("Filter chips")}${stage('<div style="display:flex;gap:8px;flex-wrap:wrap"><span class="ns-tag ns-tag--blue">Region: EU<button aria-label="Remove Region: EU">×</button></span><span class="ns-tag ns-tag--blue">Status: Active<button aria-label="Remove Status: Active">×</button></span><button class="ns-btn ns-btn--ghost ns-btn--sm">Clear all</button></div>')}${h2("Rules")}<ul><li>Filter results live as people choose; do not require an Apply button for fewer than 5 filters.</li><li>Show a result count after every change, announced in a live region.</li><li>Global search lives in the header and opens with <kbd>⌘K</kbd> or <kbd>/</kbd>.</li></ul>`);
  pattern("errors", "Errors", "Good errors say what happened, why, and how to fix it, at the level where the problem happened.", () => `${h2("Levels")}${table(["Level", "Component", "Example"], [["Field", "Helper text in error state", "Enter a full email address"], ["Section", "Inline notification", "3 integrations failed to sync"], ["App", "Alert banner", "Authentication service is down"], ["Page", "Error page", "404, 500, permission denied"]])}${h2("Error pages")}<div class="grid grid-3">${[["404", "Page not found", "The link may be old or mistyped."], ["500", "Something broke", "We have been alerted. Try again in a minute."], ["403", "No access", "Ask a workspace admin for the Partner Viewer role."]].map(([c, t, b]) => `<div class="ns ns-card" style="padding:32px"><span style="font:800 48px/1 var(--ns-font-mono);background:var(--ns-gradient-brand);-webkit-background-clip:text;background-clip:text;color:transparent">${c}</span><h3 class="ns-card__title">${t}</h3><p class="ns-card__body">${b}</p><a class="ns-btn ns-btn--sm ns-btn--tertiary" href="#/">Go home</a></div>`).join("")}</div>`);

  pattern("production", "Production patterns", "Production-ready UI patterns, states, and system specifications from the Figma Patterns page.", () => `
${h2("Modal dialog")}${stage(`<div class="ns-modal ns-modal--inline" role="dialog" aria-labelledby="pp-m" style="--_w:612px"><div class="ns-modal__head"><div><span class="ns-badge ns-badge--negative ns-badge--sm" style="margin-bottom:10px">Destructive</span><h2 class="ns-modal__title" id="pp-m">Confirm Destructive Action</h2></div></div><div class="ns-modal__body">This action cannot be undone. This will permanently delete the selected database nodes and terminate active routing tunnels.</div><div class="ns-modal__foot"><button class="ns-btn ns-btn--ghost">Cancel</button><button class="ns-btn ns-btn--danger">Confirm Purge</button></div></div>`, { label: "Pattern / Modal Dialog" })}<p><strong>Usage:</strong> use for high-impact confirmation flows. Trigger only via primary buttons.</p>
${h2("Alerts and toasts")}${stage(`<div style="display:grid;gap:12px;width:100%;max-width:612px"><div class="ns-alert ns-alert--warning"><span class="ns-alert__icon">${NS.svgIcon("alert", 16)}</span><div><p class="ns-alert__title">Inbound Network Traffic Anomaly</p><p class="ns-alert__desc">Cluster US-EAST showing 400% spikes. Automatic scaling triggered.</p></div><div class="ns-alert__end"><button class="ns-alert__close" aria-label="Dismiss">\u00d7</button></div></div><div class="ns-notice ns-notice--toast ns-notice--success" style="justify-self:end"><span class="ns-notice__icon">\u2713</span><div><p class="ns-notice__title">Deployment Successful</p><p class="ns-notice__body">Node-04 online \u00b7 12ms</p></div><button class="ns-notice__close" aria-label="Dismiss">\u00d7</button></div></div>`, { label: "Pattern / Toast Stack" })}
${h2("Data table states")}${stage(`<div class="ns-table-wrap" style="width:100%"><table class="ns-table"><thead><tr><th>Node ID</th><th>Routing endpoint</th><th>Status</th><th class="num">Load</th></tr></thead><tbody><tr><td style="font-family:var(--ns-font-mono)">NS-0091</td><td>api.us-east.northstar.dev</td><td><span class="ns-dot ns-dot--success">Healthy</span></td><td class="num" style="color:var(--ns-status-success)">22.4%</td></tr><tr><td style="font-family:var(--ns-font-mono)">NS-0092</td><td>db.eu-west.northstar.dev</td><td><span class="ns-dot ns-dot--error">Overloaded</span></td><td class="num" style="color:var(--ns-status-error)">94.8%</td></tr></tbody></table><div class="ns-table-bar" style="border-top:1px solid var(--ns-border-subtle);border-bottom:0"><span class="ns-helper">Showing 1-2 of 48 resources</span><span style="display:flex;gap:8px"><button class="ns-btn ns-btn--sm ns-btn--outline" disabled>Prev</button><button class="ns-btn ns-btn--sm ns-btn--outline">Next</button></span></div></div>`, { block: true, label: "Pattern / Data Table", code: false })}
${h2("System indicators")}${stage(`<div class="ns-card" style="width:352px;grid-template-columns:1fr 1fr;display:grid;gap:18px">${[["Active channels", "14,809", ""], ["Alerts", "03", "var(--ns-status-error)"], ["CPU efficiency", "98.2%", "var(--ns-text-accent)"]].map(([l, v, c]) => `<div><span class="ns-kpi__label">${l}</span><div style="font:800 26px/1.2 var(--ns-font-sans);${c ? "color:" + c : ""}">${v}</div></div>`).join("")}</div>`, { label: "Pattern / System Indicators" })}${notice("info", "Fixed from the Figma frame", "In the Figma frame the Alerts value overlaps the text \"of 48 resources\". Here each indicator gets its own grid cell.")}
${h2("Feedback and placeholders")}${stage(`<div style="display:grid;grid-template-columns:200px 1fr;gap:24px;align-items:center;width:100%;max-width:612px"><div style="display:grid;gap:8px"><div class="ns-skel" style="height:14px;width:60%"></div><div class="ns-skel" style="height:56px"></div><div class="ns-skel" style="height:10px"></div></div><div><h3 style="margin:0 0 6px;font:700 16px/1.3 var(--ns-font-sans)">No active tunnels discovered</h3><p style="margin:0 0 12px;color:var(--ns-text-secondary);font-size:14px">Deploy a northstar routing agent to initialize system streams.</p><button class="ns-btn ns-btn--sm">Deploy agent</button></div></div>`, { label: "Pattern / Empty State" })}
${h2("Navigation and breadcrumbs")}${stage(`<div style="display:grid;gap:14px;width:100%;max-width:612px"><ol class="ns-breadcrumb"><li><a href="#/">Cluster Root</a></li><li><a href="#/">US-EAST</a></li><li aria-current="page">NS-0091</li></ol><div class="ns-tabs" role="tablist"><button class="ns-tab" role="tab" aria-selected="true">Label 1</button><button class="ns-tab" role="tab" aria-selected="false">Label 2</button></div><label class="ns-check ns-check--radio"><input type="radio" checked/> Use persistent socket connections</label></div>`, { label: "Pattern / Breadcrumb Navigation" })}
${h2("Input component states")}${stage(`<div style="display:flex;gap:16px;flex-wrap:wrap;align-items:end"><div class="ns-field" style="width:260px"><label class="ns-label">Default endpoint value</label><input class="ns-input ns-input--md" value="https://api.northstar.dev"/></div><div class="ns-field"><span class="ns-label">Routing target</span><div class="ns-dd" data-dd><button class="ns-dd__trigger" aria-haspopup="listbox" aria-expanded="false">us-east-1<span class="caret"></span></button><ul class="ns-dd__menu" role="listbox"><li><button class="ns-dd__item" role="option" aria-selected="true">us-east-1</button></li><li><button class="ns-dd__item" role="option">eu-west-1</button></li></ul></div></div></div>`, { label: "Pattern / Field Group" })}
${h2("Skeleton")}<div class="grid grid-3">${[["Text", '<div style="display:grid;gap:10px"><div class="ns-skel" style="height:16px;width:70%"></div><div class="ns-skel" style="height:10px"></div><div class="ns-skel" style="height:10px;width:90%"></div><div class="ns-skel" style="height:10px;width:60%"></div></div>'], ["Card", '<div style="display:grid;gap:10px"><div class="ns-skel" style="height:72px"></div><div class="ns-skel" style="height:14px;width:60%"></div><div class="ns-skel" style="height:10px;width:40%"></div></div>'], ["Table", '<div style="display:grid;gap:8px">' + Array.from({ length: 5 }, (_, i) => `<div style="display:grid;grid-template-columns:2fr 1fr 1fr;gap:8px"><div class="ns-skel" style="height:${i ? 10 : 12}px"></div><div class="ns-skel" style="height:${i ? 10 : 12}px"></div><div class="ns-skel" style="height:${i ? 10 : 12}px"></div></div>`).join("") + "</div>"]].map(([t, h]) => `<div class="ns-card"><span class="ns-kpi__label">Type = ${t}</span>${h}</div>`).join("")}</div>
${h2("Progress indicator")}<div class="grid grid-2">${[["Linear", "Determinate", '<div class="ns-progress"><div class="ns-progress__meta"><span>Syncing</span><span>64%</span></div><div class="ns-progress__track"><div class="ns-progress__bar" style="--_v:64%"></div></div></div>'], ["Linear", "Indeterminate", '<div class="ns-progress ns-progress--indeterminate"><div class="ns-progress__meta"><span>Syncing</span></div><div class="ns-progress__track"><div class="ns-progress__bar"></div></div></div>'], ["Circular", "Determinate", '<div class="ns-ring" style="--_v:64"><span>64%</span></div>'], ["Circular", "Indeterminate", '<span class="ns-spin" style="width:48px;height:48px;border-width:5px"></span>']].map(([a, b, h]) => `<div class="ns-card"><span class="ns-kpi__label">${a} \u00b7 ${b}</span><div class="ns" style="min-height:72px;display:grid;align-items:center">${h}</div></div>`).join("")}</div>`);

  pattern("create-partner", "Create partner workflow", "A composed form showing entry, actionable validation and a success outcome on one surface. Synced from the Figma workflow showcase; all partner values are demo data.", () => {
    const wf = NS.WORKFLOWS["create-partner"];
    const st = (key, title) => {
      const err = key === "error", ok = key === "success", id = "cp-" + key;
      const banner = err ? `<div class="ns-alert ns-alert--error" role="alert"><span class="ns-alert__icon">${NS.svgIcon("alert", 16)}</span><div><p class="ns-alert__title">Partner not created</p><p class="ns-alert__desc">Check Billing email. Enter a complete address, then create the partner again.</p><div class="ns-alert__actions"><button type="button" class="ns-btn ns-btn--sm ns-btn--outline" onclick="document.getElementById('${id}-email').focus()">Review email</button><button type="button" class="ns-btn ns-btn--sm ns-btn--ghost">Keep editing</button></div></div></div>`
        : ok ? `<div class="ns-alert ns-alert--success" role="status"><span class="ns-alert__icon">${NS.svgIcon("check", 16)}</span><div><p class="ns-alert__title">Partner created · demo outcome</p><p class="ns-alert__desc">Atlas Works is ready. Billing email and Growth tier are saved in this illustrative state.</p></div></div>` : "";
      return `<form class="ns cp-state" onsubmit="event.preventDefault()" aria-labelledby="${id}-t">
<p class="spec-label">${title} · demo data</p><h3 class="cp-state__title" id="${id}-t">Create partner</h3><p class="cp-state__copy">Add a partner and set their billing preferences.</p>${banner}
<div class="ns-field"><label class="ns-label" for="${id}-co">Company name *</label><input class="ns-input" id="${id}-co" required value="Atlas Works"/></div>
<div class="ns-field"><label class="ns-label" for="${id}-tier">Tier *</label><select class="ns-select" id="${id}-tier" required><option>Starter</option><option selected>Growth</option><option>Enterprise</option><option>Custom</option></select></div>
<div class="ns-field${err ? " is-error" : ""}"><label class="ns-label" for="${id}-email">Billing email *</label><input class="ns-input" type="email" id="${id}-email" required value="${err ? "billing@" : "billing@atlas.example"}"${err ? ' aria-invalid="true"' : ""} aria-describedby="${id}-eh"/><span class="ns-helper" id="${id}-eh">${err ? "Enter a complete email address, for example billing@atlas.example." : "Invoices will be sent to this address."}</span></div>
<label class="ns-check"><input type="checkbox" checked/> Send welcome kit</label>
<div style="display:flex;gap:10px"><button class="ns-btn"${ok ? " disabled" : ""}>Create partner</button><button type="button" class="ns-btn ns-btn--ghost">Cancel</button></div>
<p class="cp-state__note">${ok ? "Proposed success behavior: prevent duplicate submit while preserving the result. Next action: open partner record." : "Required fields are marked *. Cancel leaves without creating a partner; persistence rules require application decisions."}</p></form>`;
    };
    let h = `<div class="spec-head"><p class="spec-label">${NS.esc(wf.category)} · ${NS.esc(wf.revision)}</p><div class="spec-status">${Object.entries(wf.meta).map(([k, v]) => `<span><b>${NS.esc(k)}</b>${NS.esc(String(v).replace(/^Owner: /, ""))}</span>`).join("")}</div><p><a href="${FIGMA}?node-id=${wf.nodeId.replace(":", "-")}" target="_blank" rel="noopener">Open the workflow showcase in Figma ↗</a></p></div>`;
    h += `${h2("Form states")}<p>Default, validation error and success, rebuilt with live NorthStar components. Tier uses the native Select, as the online forms pattern does.</p><div class="cp-states">${st("default", "Default")}${st("error", "Validation error")}${st("success", "Success")}</div>`;
    wf.sections.forEach((s) => {
      h += h2(`${s.number} ${s.heading}`);
      s.blocks.forEach((b) => { if (!(b.type === "example" && /^Form state/.test(b.label))) h += NS.renderSpecBlock(b); });
    });
    return h + `<p class="spec-foot">${wf.footer.map(NS.esc).join(" · ")}</p>`;
  });

  /* DATA VIZ */
  P("data-viz", { title: "Data visualization", lede: "Charts in NorthStar are built for dense, dark dashboards: high-contrast categorical color, quiet axes, and direct labels.", body: () => `${h2("Principles")}${cards([{ title: "Direct labels", color: "teal", body: "Label series at the line end instead of relying on a legend.", href: "#/data-viz/charts" }, { title: "Quiet structure", color: "purple", body: "Axes and gridlines use border/subtle; data carries the color.", href: "#/data-viz/charts" }, { title: "Ordered color", color: "blue", body: "Apply the categorical palette in order; never skip for taste.", href: "#/data-viz/palettes" }])}${h2("Resources")}${cards([{ title: "Color palettes", body: "Categorical, sequential, and alert palettes.", href: "#/data-viz/palettes", go: "View" }, { title: "Sankey chart", body: "New in v1.4: flow between stages.", href: "#/data-viz/sankey", go: "View" }, { title: "Chart types", body: "Bar, line, donut, sparkline.", href: "#/data-viz/charts", go: "View" }])}` });
  P("data-viz/palettes", { title: "Color palettes", lede: "Seven categorical colors tuned for dark surfaces. Apply them in order.", body: () => `${h2("Categorical")}<div class="grid" style="grid-template-columns:repeat(7,minmax(0,1fr))">${Array.from({ length: 7 }, (_, i) => swatchBtn(`--ns-viz-${i + 1}`, `Viz ${i + 1}`)).join("")}</div>${h2("Sequential")}<div style="display:flex;height:48px;border-radius:8px;overflow:hidden;margin-bottom:24px">${[10, 22, 36, 52, 68, 84, 100].map((p) => `<i style="flex:1;background:color-mix(in srgb,var(--ns-teal-500) ${p}%,var(--ns-background-primary))"></i>`).join("")}</div>${h2("Alert")}<div class="grid grid-4">${swatchBtn("--ns-status-success", "Success")}${swatchBtn("--ns-status-warning", "Warning")}${swatchBtn("--ns-status-error", "Error")}${swatchBtn("--ns-status-info", "Info")}</div>` });
  P("data-viz/sankey", {
    title: "Sankey chart", lede: "Sankey charts show how a quantity flows between stages. Link width is proportional to value.", status: "New",
    body: () => `${h2("Live demo")}<div class="stage"><div class="stage__bar"><span class="lbl">Partner pipeline flow</span><div class="ns seg" id="sk-seg">${["S", "M", "L"].map((s, i) => `<button data-s="${s}" aria-pressed="${i === 1}">${s}</button>`).join("")}<button data-bgt aria-pressed="true">Background</button></div></div><div class="stage__canvas is-block" id="sk-wrap" style="padding:32px"><div id="sk"></div></div></div>
${h2("Variants")}${table(["Property", "Values", "Use"], [["Size", "S, M, L", "Tile, card, full-width panel"], ["Data", "Minimum, Maximum", "3 to 4 nodes per stage, up to 8"], ["Background", "Yes, No", "Standalone vs inside a card"]])}
${h2("When to use")}<ul><li>Conversion or routing between two to four stages.</li><li>Showing where volume is lost or redistributed.</li></ul>${h2("When not to use")}<ul><li>More than four stages or eight nodes per stage: it becomes unreadable.</li><li>Comparing exact values: use a bar chart or table.</li></ul>`,
    init: () => {
      let size = "M", bg = true;
      const draw = () => { const w = { S: 420, M: 680, L: 920 }[size]; document.getElementById("sk").innerHTML = NS.sankey(w, size === "S" ? 220 : 320); document.getElementById("sk-wrap").style.background = bg ? "var(--ns-background-elevated)" : ""; };
      document.querySelectorAll("#sk-seg button").forEach((b) => b.addEventListener("click", () => { if (b.dataset.s) { size = b.dataset.s; document.querySelectorAll("#sk-seg [data-s]").forEach((x) => x.setAttribute("aria-pressed", x === b)); } else { bg = !bg; b.setAttribute("aria-pressed", bg); } draw(); }));
      draw();
    },
  });
  NS.sankey = function (W, H) {
    const cols = [[["Leads", 1200]], [["Qualified", 700], ["Nurture", 350], ["Lost", 150]], [["Won", 420], ["Open", 380], ["Churned", 250]]];
    const links = [[0, 0, 1, 0, 700], [0, 0, 1, 1, 350], [0, 0, 1, 2, 150], [1, 0, 2, 0, 380], [1, 0, 2, 1, 220], [1, 0, 2, 2, 100], [1, 1, 2, 0, 40], [1, 1, 2, 1, 160], [1, 1, 2, 2, 150]];
    const colors = ["var(--ns-viz-1)", "var(--ns-viz-2)", "var(--ns-viz-3)", "var(--ns-viz-4)", "var(--ns-viz-5)", "var(--ns-viz-6)"];
    const nodeW = 12, pad = 18, total = 1200, scale = (H - pad * 4) / total;
    const pos = cols.map((col, ci) => { let y = 0; const x = ci * ((W - nodeW - 110) / (cols.length - 1)); return col.map(([n, v]) => { const h = v * scale; const o = { n, v, x, y, h, outY: y, inY: y }; y += h + pad; return o; }); });
    let svg = `<svg viewBox="0 0 ${W} ${H}" width="100%" style="max-width:${W}px;display:block;margin:0 auto" role="img" aria-label="Sankey chart: 1,200 leads flow to qualified, nurture, and lost, then to won, open, and churned">`;
    links.forEach(([c1, n1, c2, n2, v], i) => { const a = pos[c1][n1], b = pos[c2][n2], h = v * scale; const x1 = a.x + nodeW, x2 = b.x, y1 = a.outY + h / 2, y2 = b.inY + h / 2; a.outY += h; b.inY += h; const mx = (x1 + x2) / 2; svg += `<path d="M${x1},${y1} C${mx},${y1} ${mx},${y2} ${x2},${y2}" fill="none" stroke="${colors[n1 + (c1 ? 1 : 0)]}" stroke-opacity=".38" stroke-width="${Math.max(h, 1)}"><title>${a.n} → ${b.n}: ${v}</title></path>`; });
    pos.forEach((col, ci) => col.forEach((o, ni) => { svg += `<rect x="${o.x}" y="${o.y}" width="${nodeW}" height="${o.h}" rx="2" fill="${colors[ci === 0 ? 0 : ni + (ci === 1 ? 1 : 0)]}"/><text x="${o.x + nodeW + 8}" y="${o.y + o.h / 2}" dominant-baseline="middle" fill="var(--ns-text-primary)" font-family="var(--ns-font-sans)" font-size="12" font-weight="600">${o.n} <tspan fill="var(--ns-text-tertiary)" font-family="var(--ns-font-mono)" font-weight="400">${o.v}</tspan></text>`; }));
    return svg + "</svg>";
  };
  P("data-viz/charts", { title: "Chart types", lede: "Pick the chart by the question it answers.", body: () => `${h2("Choosing")}${table(["Question", "Chart"], [["How do categories compare?", "Bar"], ["How does it change over time?", "Line, sparkline"], ["What share of the whole?", "Donut (5 slices max)"], ["Where does volume flow?", "Sankey"]])}${h2("Bar")}${stage(`<div class="bars" style="width:100%;max-width:520px">${[40, 72, 55, 90, 64, 30, 80, 48].map((v) => `<i style="height:${v}%"></i>`).join("")}</div>`, { code: false, label: "Bar" })}${h2("Donut")}${stage(`<div style="display:flex;gap:32px;align-items:center"><div style="width:140px;height:140px;border-radius:50%;background:conic-gradient(var(--ns-viz-1) 0 42%,var(--ns-viz-2) 0 68%,var(--ns-viz-3) 0 84%,var(--ns-viz-4) 0 100%);mask:radial-gradient(circle,transparent 46%,#000 47%);-webkit-mask:radial-gradient(circle,transparent 46%,#000 47%)" role="img" aria-label="Donut: Enterprise 42%, Mid-market 26%, SMB 16%, Public 16%"></div><div style="display:grid;gap:8px;font-size:13px">${[["Enterprise", 42, 1], ["Mid-market", 26, 2], ["SMB", 16, 3], ["Public", 16, 4]].map(([n, v, i]) => `<span><span class="chip" style="background:var(--ns-viz-${i})"></span>${n} <b>${v}%</b></span>`).join("")}</div></div>`, { code: false, label: "Donut" })}${h2("Sparkline")}${stage(NS.sparkline([4, 6, 5, 8, 7, 11, 9, 13, 12, 16], 240, 48), { code: false, label: "Sparkline" })}` });
  NS.sparkline = (d, w, h) => { const mx = Math.max(...d), mn = Math.min(...d); const pts = d.map((v, i) => `${(i / (d.length - 1)) * w},${h - ((v - mn) / (mx - mn)) * (h - 6) - 3}`).join(" "); return `<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-label="Trend rising"><polyline points="${pts}" fill="none" stroke="var(--ns-viz-1)" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"/></svg>`; };

  /* FLOORPLANS */
  const shell = (active, inner) => `<div class="fp ns"><nav class="fp__nav" aria-label="Floorplan nav"><span class="brand"><span class="brand__dot"></span>NORTHSTAR</span>${["Dashboard", "Partners", "Approvals", "Projects", "Settings"].map((n) => `<a class="${n === active ? "on" : ""}">${n}</a>`).join("")}</nav><main class="fp__main">${inner}</main></div>`;
  NS.FLOORPLANS = {
    dashboard: ["Dashboard", "KPI tiles, trend, mix, and a partner table. One job per tile.", () => shell("Dashboard", `<div class="fp__head"><div><small>Partner portal</small><h3>Good morning, Alex</h3></div><div style="display:flex;gap:8px"><select class="ns-select ns-input--sm" style="width:140px;min-height:32px" aria-label="Range"><option>Last 30 days</option></select><button class="ns-btn ns-btn--sm">Export</button></div></div><div class="fp__grid">${NS.widget("circle-M")}${NS.widget("line-M")}${NS.widget("bubble-row")}${NS.widget("column-L")}${NS.widget("combined-M")}</div>${NS.COMPONENTS.find((c) => c.id === "data-table").playground.render({ size: "Compact", batch: false })}`)],
    "analytical-list": ["Analytical list", "Filter bar, sortable table, bulk actions, and pagination for working through many records.", () => shell("Partners", `<div class="fp__head"><div><small>Partners</small><h3>All partners</h3></div><button class="ns-btn ns-btn--sm">Add partner</button></div><div style="display:flex;gap:8px;flex-wrap:wrap"><div class="ns-search" style="flex:1;min-width:200px">${NS.icon.search}<input class="ns-input ns-input--sm" placeholder="Search partners" aria-label="Search partners"/></div><span class="ns-tag ns-tag--blue">Tier: Gold<button aria-label="Remove">×</button></span><span class="ns-tag ns-tag--blue">Region: EU<button aria-label="Remove">×</button></span></div>${NS.COMPONENTS.find((c) => c.id === "data-table").playground.render({ size: "Default", batch: true })}<nav class="ns-pagination" style="justify-content:space-between"><span>1-5 of 288</span><span><button class="ns-page" disabled>‹</button><button class="ns-page" aria-current="page">1</button><button class="ns-page">2</button><button class="ns-page">3</button><button class="ns-page">›</button></span></nav>`)],
    "object-detail": ["Object detail", "Object header with status and actions, tab strip, and structured detail sections.", () => shell("Partners", `<ol class="ns-breadcrumb"><li><a href="#/floorplans/analytical-list">Partners</a></li><li aria-current="page">Acme Corp</li></ol><div class="fp__head"><div style="display:flex;gap:14px;align-items:center"><span class="ns-avatar ns-avatar--lg ns-avatar--brand">AC</span><div><h3 style="margin:0">Acme Corp</h3><span class="ns-dot ns-dot--success">Active</span> <span class="ns-tag ns-tag--sm ns-tag--yellow">Gold</span></div></div><div style="display:flex;gap:8px"><button class="ns-btn ns-btn--sm ns-btn--tertiary">Edit</button><button class="ns-btn ns-btn--sm">New project</button></div></div><div class="ns-tabs" role="tablist"><button class="ns-tab" role="tab" aria-selected="true">Overview</button><button class="ns-tab" role="tab" aria-selected="false">Integrations <span class="ns-count">14</span></button><button class="ns-tab" role="tab" aria-selected="false">Billing</button><button class="ns-tab" role="tab" aria-selected="false">Audit log</button></div><div class="grid grid-3">${[["MRR", "$12,400"], ["Renewal", "42 days"], ["Health", "92 / 100"]].map(([l, v]) => `<div class="ns-kpi"><span class="ns-kpi__label">${l}</span><span class="ns-kpi__value" style="font-size:24px">${v}</span></div>`).join("")}</div><div class="grid grid-2"><div class="ns-card"><div class="ns-card__strip">Details</div>${[["Owner", "Alex Park"], ["Region", "us-east-1"], ["Since", "March 2023"], ["Contract", "MSA-2291"]].map(([k, v]) => `<div style="display:flex;justify-content:space-between;font-size:14px"><span style="color:var(--ns-text-tertiary)">${k}</span><span>${v}</span></div>`).join("")}</div><div class="ns-card"><div class="ns-card__strip">Recent activity</div><div class="ns-notice ns-notice--success"><span class="ns-notice__icon">✓</span><div><p class="ns-notice__title">Salesforce sync complete</p><p class="ns-notice__body">2 hours ago</p></div><span></span></div><div class="ns-notice ns-notice--warning"><span class="ns-notice__icon">!</span><div><p class="ns-notice__title">API quota at 85%</p><p class="ns-notice__body">Yesterday</p></div><span></span></div></div></div>`)],
    wizard: ["Guided wizard", "A five-step progress rail, one task per step, validation before moving on, and clear back and next.", () => shell("Projects", `<div class="fp__head"><div><small>New project</small><h3>Connect a data source</h3></div></div><ol class="ns-steps"><li class="is-done"><b>Details</b>Done</li><li class="is-done"><b>Source</b>Done</li><li class="is-current" aria-current="step"><b>Credentials</b>Current</li><li><b>Mapping</b></li><li><b>Review</b></li></ol><div class="ns-card" style="max-width:520px"><h3 class="ns-card__title">Credentials</h3><div class="ns-field"><label class="ns-label">API endpoint</label><input class="ns-input" value="https://api.acme.com/v2"/></div><div class="ns-field is-error"><label class="ns-label">API key</label><input class="ns-input" type="password" value="abc" aria-invalid="true"/><span class="ns-helper">Key must be 32 characters.</span></div><div style="display:flex;justify-content:space-between"><button class="ns-btn ns-btn--tertiary">Back</button><button class="ns-btn">Next: Mapping</button></div></div>`)],
    "approval-queue": ["Approval queue", "Risk meters, flag badges, and accept or reject actions for fast, careful review.", () => shell("Approvals", `<div class="fp__head"><div><small>Approvals</small><h3>37 requests waiting</h3></div><div class="ns-tabs ns-tabs--pill" role="tablist"><button class="ns-tab" aria-selected="true">Pending</button><button class="ns-tab" aria-selected="false">Approved</button><button class="ns-tab" aria-selected="false">Rejected</button></div></div>${[["Zeta Inc", "Tier upgrade to Platinum", 82, "error", "High risk"], ["Beta LLC", "Add 3 API keys", 45, "warning", "Review"], ["Globex", "Region change to eu-central-1", 18, "success", "Low risk"]].map(([n, r, v, k, l]) => `<div class="ns-card" style="grid-template-columns:auto 1fr 180px auto;align-items:center;display:grid;gap:16px"><span class="ns-avatar">${n.slice(0, 2).toUpperCase()}</span><div><b>${n}</b><div style="font-size:13px;color:var(--ns-text-secondary)">${r}</div></div><div class="ns-progress ns-progress--${k === "success" ? "" : k}"><div class="ns-progress__meta"><span class="ns-dot ns-dot--${k}">${l}</span><span>${v}</span></div><div class="ns-progress__track"><div class="ns-progress__bar" style="--_v:${v}%"></div></div></div><div style="display:flex;gap:8px"><button class="ns-btn ns-btn--sm ns-btn--tertiary" data-toast="Rejected ${n}" data-kind="error">Reject</button><button class="ns-btn ns-btn--sm" data-toast="Approved ${n}" data-kind="success">Approve</button></div></div>`).join("")}`)],
  };
  P("floorplans", { title: "Floorplans", lede: "Floorplans are fully assembled page templates. Start from one, then swap content. Every floorplan renders shell-free in embed mode.", body: () => cards(Object.entries(NS.FLOORPLANS).map(([k, [t, d]]) => ({ title: t, body: d, href: "#/floorplans/" + k, go: "Open" })), 3) });
  Object.entries(NS.FLOORPLANS).forEach(([k, [t, d, render]]) => P("floorplans/" + k, { title: t, lede: d, body: () => `<div class="fp-frame"><div class="fp-frame__bar"><i></i><i></i><i></i><span>northstar.app/${k}</span><a class="ns-btn ns-btn--ghost ns-btn--sm" href="?embed#/floorplans/${k}" target="_blank" rel="noopener">Open embed ↗</a></div>${render()}</div>${h2("Built from")}<p>Side navigation, data table, KPI tiles, tabs, notifications, buttons, tags, and badges. Every value is a token, so the whole floorplan follows theme and token edits.</p>` }));

  /* ACCESSIBILITY */
  P("accessibility", { title: "Accessibility principles", lede: "NorthStar targets WCAG 2.2 Level AA, with special care for dark-mode contrast, keyboard navigation, and focus clarity.", body: () => `${h2("Principles")}${cards([{ title: "Perceivable", color: "teal", body: "4.5:1 text contrast, 3:1 for UI and focus, never color alone.", href: "#/accessibility/contrast" }, { title: "Operable", color: "purple", body: "Every action works by keyboard with a visible focus ring.", href: "#/accessibility/checklist" }, { title: "Understandable", color: "blue", body: "Plain labels, predictable patterns, errors that explain the fix.", href: "#/patterns/errors" }])}${h2("Focus specifications")}${stage('<button class="ns-btn" style="outline:2px solid var(--ns-focus-ring);outline-offset:2px">Focused button</button><div class="ns-field" style="width:220px"><input class="ns-input" style="border-color:var(--ns-focus-ring);box-shadow:0 0 0 1px var(--ns-focus-ring)" value="Focused input"/></div>', { label: "2px ring, 2px offset, focus/ring token", code: false })}${notice("info", "Focus outlines are critical for keyboard navigation", "Never remove outlines without a replacement that meets 3:1 against adjacent colors.")}` });
  P("accessibility/checklist", {
    title: "Checklist", lede: "Run this before every release. Your progress is saved in this browser.",
    body: () => { const items = { Color: ["Text meets 4.5:1 (3:1 for 18px+ bold)", "UI boundaries and focus meet 3:1", "Status is never color-only"], Keyboard: ["Every action reachable by Tab", "Focus order matches visual order", "Modals trap focus and restore it", "No keyboard traps elsewhere"], "Screen readers": ["All inputs have visible labels", "Icon-only buttons have names", "Live regions announce async changes", "Landmarks: header, nav, main, footer"], Content: ["Headings are nested in order", "Link text makes sense out of context", "Errors explain how to fix"] }; let i = 0; return Object.entries(items).map(([g, list]) => h2(g) + `<div class="ns" style="display:grid;gap:12px">${list.map((t) => `<label class="ns-check"><input type="checkbox" data-a11y="${i++}"/> ${t}</label>`).join("")}</div>`).join("") + `<p class="mt" id="a11y-score" style="color:var(--ns-text-tertiary)"></p>`; },
    init: () => { const KEY = "ns-a11y"; let s = []; try { s = JSON.parse(localStorage.getItem(KEY) || "[]"); } catch (e) {} const b = document.querySelectorAll("[data-a11y]"); const sc = () => (document.getElementById("a11y-score").textContent = `${[...b].filter((x) => x.checked).length} of ${b.length} checks passed.`); b.forEach((x) => { x.checked = s.includes(+x.dataset.a11y); x.addEventListener("change", () => { try { localStorage.setItem(KEY, JSON.stringify([...b].filter((y) => y.checked).map((y) => +y.dataset.a11y))); } catch (e) {} sc(); }); }); sc(); },
  });
  P("accessibility/wcag", { title: "WCAG mapping", lede: "How NorthStar foundations and components meet specific WCAG 2.2 AA success criteria.", body: () => `${h2("Criteria")}${table(["Criterion", "Level", "How NorthStar meets it"], [["1.3.1 Info and relationships", "A", "Labels, fieldsets, table headers, landmarks in every component"], ["1.4.1 Use of color", "A", "Badges and tags always carry text"], ["1.4.3 Contrast (minimum)", "AA", "Text roles tested against every surface role"], ["1.4.11 Non-text contrast", "AA", "Borders, focus rings, and toggles at 3:1"], ["2.1.1 Keyboard", "A", "Documented keyboard map per component"], ["2.4.7 Focus visible", "AA", "2px focus/ring with 2px offset"], ["2.4.11 Focus not obscured", "AA", "Sticky header offsets scroll padding"], ["2.5.8 Target size (minimum)", "AA", "24px minimum, 32 to 40px default"], ["3.3.1 Error identification", "A", "Inline error text, aria-invalid"], ["4.1.3 Status messages", "AA", "Notifications use status and alert roles"]])}` });
  P("accessibility/contrast", {
    title: "Contrast checker", lede: "Live WCAG contrast for NorthStar's text and UI roles on every surface. Change the theme or edit tokens and the ratios recompute.",
    body: () => `<div id="cc" class="cc-grid"></div>${h2("Check any pair")}<div class="ns" style="display:flex;gap:16px;align-items:end;flex-wrap:wrap;margin-bottom:24px"><div class="ns-field"><label class="ns-label" for="cc-fg">Foreground</label><input id="cc-fg" type="color" value="#01f1e3" style="width:80px;height:40px;border:0;background:none"/></div><div class="ns-field"><label class="ns-label" for="cc-bg">Background</label><input id="cc-bg" type="color" value="#191932" style="width:80px;height:40px;border:0;background:none"/></div><div id="cc-out" style="font:800 32px/1 var(--ns-font-mono)"></div></div>`,
    init: () => {
      const pairs = [["--ns-text-primary", "--ns-background-primary"], ["--ns-text-secondary", "--ns-background-primary"], ["--ns-text-tertiary", "--ns-background-surface"], ["--ns-text-primary", "--ns-background-elevated"], ["--ns-text-link", "--ns-background-primary"], ["--ns-text-accent", "--ns-background-elevated"], ["--ns-text-on-color", "--ns-interactive-primary"], ["--ns-text-on-color", "--ns-interactive-secondary"], ["--ns-status-success", "--ns-background-surface"], ["--ns-status-warning", "--ns-background-surface"], ["--ns-status-error", "--ns-background-surface"], ["--ns-focus-ring", "--ns-background-primary"]];
      const grade = (r) => (r >= 7 ? ["AAA", "green"] : r >= 4.5 ? ["AA", "green"] : r >= 3 ? ["AA large / UI", "yellow"] : ["Fail", "red"]);
      document.getElementById("cc").innerHTML = pairs.map(([f, b]) => { const r = NS.contrast(NS.tokenValue(f), NS.tokenValue(b)); const [g, c] = grade(r); return `<div class="cc"><div class="cc__demo" style="color:var(${f});background:var(${b})">Aa ${r.toFixed(2)}:1<small>${f.replace("--ns-", "")}</small></div><div class="cc__meta"><span>on ${b.replace("--ns-", "")}</span><span class="ns ns-tag ns-tag--sm ns-tag--${c}">${g}</span></div></div>`; }).join("");
      const run = () => { const r = NS.contrast(document.getElementById("cc-fg").value, document.getElementById("cc-bg").value); const [g, c] = grade(r); document.getElementById("cc-out").innerHTML = `${r.toFixed(2)}:1 <span class="ns ns-tag ns-tag--${c}">${g}</span>`; };
      ["cc-fg", "cc-bg"].forEach((id) => document.getElementById(id).addEventListener("input", run)); run();
    },
  });

  /* COMMUNITY */
  P("community/contributing", { title: "Contributing", lede: "NorthStar grows through contributions from product teams. Here is how an idea becomes a component.", body: () => `${h2("Process")}<ol class="ns-steps" style="margin-bottom:32px"><li class="is-done"><b>Propose</b>Open an issue with the problem</li><li class="is-done"><b>Review</b>Weekly design system triage</li><li class="is-current"><b>Build</b>Figma + code together</li><li><b>Test</b>A11y and visual regression</li><li><b>Ship</b>Release notes</li></ol>${h2("Definition of done")}<ul><li>Figma component with variants bound to variables.</li><li>React and HTML/CSS implementations reading only tokens.</li><li>Docs page: Usage, Style, Code, Accessibility tabs.</li><li>Keyboard map and screen reader test notes.</li><li>Dark and light screenshots in the pull request.</li></ul>` });
  P("community/governance", { title: "Governance", lede: "Who decides, how changes are versioned, and how breaking changes are handled.", body: () => `${h2("Versioning")}${table(["Change", "Version", "Notice"], [["Bug fix, docs", "Patch", "Release notes"], ["New component or token", "Minor", "Release notes + changelog"], ["Rename or removal", "Major", "One minor release of deprecation first"]])}${h2("Roles")}${table(["Role", "Responsibility"], [["Core team", "Roadmap, review, releases"], ["Contributors", "Proposals and pull requests"], ["Security board", "Reviews components that handle credentials or PII"]])}` });
  P("community/support", { title: "Support", lede: "Get help, report a bug, or request a component.", body: () => cards([{ title: "Slack", color: "teal", body: "#northstar-design-system for quick questions.", href: "#/community/support", go: "Join" }, { title: "GitHub issues", color: "purple", body: "Bugs and feature requests with a template.", href: "#/community/contributing", go: "Open issue" }, { title: "Office hours", color: "blue", body: "Thursdays 11:00 CT. Bring a screen, get a review.", href: "#/community/support", go: "Book" }]) });

  NS.allTokens = function () {
    const out = new Set();
    for (const sheet of document.styleSheets) { let rules; try { rules = sheet.cssRules; } catch (e) { continue; } for (const r of rules) { if (r.selectorText && /:root/.test(r.selectorText)) for (const p of r.style) if (p.startsWith("--ns-")) out.add(p); } }
    return [...out].sort();
  };
})();
